### ISSUE TITLE
Stuck on input monitoring

### ISSUE THREAD

**Issue by C9H13NO3-dev** [lanrat/homeplate#2]
Hey lanrat,

I managed to flash your homeplate software to my Inkplate, but after configuring it, it's stuck at "[INPUT] Starting input monitoring..." in the serial console - checking in my router, I don't see a wifi connection happening. This is the full boot log:

> 07:04:11.991 > [SETUP] starting, version(Mar 25 2022, 07:03:25) boot: 0
> 07:04:11.993 > ESP Chip information:
> 07:04:11.996 > This is esp32 chip with 2 CPU core(s), WiFi/BT/BLE, silicon revision 1, 4MB external flash
> 07:04:12.004 > Minimum free heap size: 4426992 bytes
> 07:04:12.007 > Heap summary for capabilities 0x00000C06:
> 07:04:12.010 >   Totals:
> 07:04:12.013 >     free 0 allocated 0 min_free 0 largest_free_block 0
> 07:04:12.018 > [ACTIVITY] startActivity(1) put into queue
> 07:04:12.021 > Wavefrom load failed! Upload new waveform in EEPROM. Using default waveform.
> 07:04:12.212 > [STATUS] Boot 1 normal
> 07:04:14.363 > [SETUP] Battery: 85% (4.54v)
> 07:04:14.907 > [SETUP] starting button task
> 07:04:14.907 > [SETUP] starting time task
> 07:04:14.910 > [TIME] RTC local time (946685005) 1999-12-31 16:03
> 07:04:14.916 > [SETUP] starting WiFi task
> 07:04:14.917 > [SETUP] starting OTA task
> 07:04:14.921 > [SETUP] starting MQTT task
> 07:04:14.923 > [MQTT] starting MQTT
> 07:04:14.923 > [SETUP] starting sleep task
> 07:04:14.926 > [SETUP] starting activities task
> 07:04:17.907 > [INPUT] Starting input monitoring...

I already double checked my wifi-credentials but that is perfectly fine...

Thanks in advance,

Epi

**Comment by lanrat** [comment]
Thanks for the report.

The problem is due to an undocumented breaking change in the [Inkplate Library](https://github.com/e-radionicacom/Inkplate-Arduino-library) that I have yet to fully identify. For the time being I set HomePlate to use the last known good version while I investigate this. If you pull the latest code from this repo and try again it should fix this problem for now.

Unrelated to this problem, If you want to fix the waveform error see this new section in the [project readme](https://github.com/lanrat/homeplate#debugging).

**Comment by C9H13NO3-dev** [comment]
Thanks you very much for solving this issue!
