### ISSUE TITLE
Just a question about MQTT push and sleep

### ISSUE THREAD

**Issue by ronnyek** [lanrat/homeplate#21]
Greetings... I set this up and actually modified what I'm doing to not integrate with homeassistant, but still using many of the bits of funcitonality (code is still largely identical).

My question is that there seems to be functionality to tell it to change display mode via mqtt. I assume since wifi is disconnected while device is sleeping, its basically going to just check for messages when it wakes and do stuff, and ultimately disconnect and sleep again. I assume if you have a 20min sleep interval, and you push a mqtt message to switch to a different screen... you wont acutally see any changes until the device wakes up (as long as 20minutes) and it picks up messages.

Other than question, everything actually seems to be working pretty well.

**Comment by lanrat** [comment]
Hello @ronnyek, you are correct.

The MQTT commands to change any state are only detected or acted upon the next time the display wakes from sleep. This can be via the timer, or via any other interrupt, such as the wake button.

Since this appears to answer your question I'll close this issue, but feel free to comment/reopen if it does not address your question.
